### ISSUE TITLE
Unable to use projectable

### ISSUE THREAD

**Issue by laluxx** [dzfrias/projectable#1]
Installed on arch with
 `cargo install projectable`
when i run prj 
`Error: Permission denied (os error 13) about ["/home/l/.local/share/wineprefixes/osu-stable/dosdevices/c:/users/l/Desktop/xos/xos-iso/iso/x86_64/airootfs/etc/audit/plugins.d"]`

**Comment by dzfrias** [comment]
Hmm. Do you know where the binary is installed to? I think there are a few possibilities for this:

1. Projectable interacts with a directory it's not supposed to. Probably not likely if it doesn't work system-wide
2. Cargo is installing it to a place where it can't be installed. Does any other `cargo install`'ed program work?
3. Projectable is trying to access files it doesn't have permissions to. There are a few places projectable tries to go aside from the project it was started in: `$XDG_CONFIG_HOME/projectable`, `$XDG_DATA_DIR/projectable`, `$PROJECTABLE_DATA_DIR` (if set), and `$PROJECTABLE_CONFIG_DIR` (if set). If any of those environment variables are point to the path in the error message, it's probably a permissions issue there. It also tries to find the project root using a glob pattern, which it does by traversing the directories upwards.

I'm mostly trying to figure out how `/home/l/.local/share/wineprefixes/osu-stable/dosdevices/c:/users/l/Desktop/xos/xos-iso/iso/x86_64/airootfs/etc/audit/plugins.d` plays into projectable when you start it. projectable shouldn't be trying to interact with that file unless you have it set as one of your config locations or unless projectable is in a directory with that file as one of the (grand)children.

Although I don't have an Arch Linux machine, I did a bit of digging and found that the `wineprefixes` thing has to do with running Windows programs on Arch. I'm not sure how much this has to do with projectable itself, though. Maybe it's a permissions problem? Unless other users experience this, then I'm not sure how much debugging I can do from the projectable side.

Sorry for the inconvenience, and I hope it works out. I'll continue to try to solve this problem in the meantime.

**Comment by laluxx** [comment]
Hello @dzfrias,

First of all, thank you for the prompt response and for taking the time to investigate the issue. Your insights are quite helpful.

I've installed projectable on Arch Linux using cargo install projectable. The binary is installed in /home/l/.cargo/bin.

In response to your queries:

- I am not aware of projectable interacting with directories it's not supposed to. However, I did notice that the error message involves a directory that seems unrelated to my project or projectable.

 - I have other binaries installed via cargo install and they are working as expected.

 - Regarding the directories projectable tries to access ($XDG_CONFIG_HOME/projectable, $XDG_DATA_DIR/projectable, $PROJECTABLE_DATA_DIR, and $PROJECTABLE_CONFIG_DIR), none of these environment variables point to the path mentioned in the error message. Also, I did not set projectable in a directory with the mentioned file.

It's puzzling how /home/l/.local/share/wineprefixes/osu-stable/dosdevices/c:/users/l/Desktop/xos/xos-iso/iso/x86_64/airootfs/etc/audit/plugins.d is involved here, as it seems unrelated to projectable. I'm wondering if this could be some kind of permission issue or an unexpected interaction.

As an additional data point, when I try executing sudo prj, the command seems to hang indefinitely without any output. I am unable to terminate it even with CTRL+C.

I understand that debugging might be challenging, especially without an Arch Linux machine. I appreciate your effort in trying to resolve this issue, and any further insights or suggestions are welcome.

I really want to integrate projectable in Neovim and Emacs. It looks great, but this issue is holding me back. Thanks for any help.

**Comment by dzfrias** [comment]
I'm stuck on the same issue as well. What's the path of the directory you're running `prj` in? projectable tries to find project roots up until `/`, which is probably a recipe for disaster. This is something I'll fix, so your issue might be related to that.

**Comment by dzfrias** [comment]
Didn't mean to close this issue! Anyway, I pushed a possible fix; it will be ready in v1.1.0, which I'll release soon. Let me know if it works. Regardless of if it does, I added some extra error contexts, so hopefully we'll be able to locate the problem easier.

**Comment by dzfrias** [comment]
v1.1.0 has been released! Let me know if the same thing appears!

**Comment by laluxx** [comment]
The issue has been resolved with the release of v1.1.0! 🎉 I've thoroughly tested it and can confirm that the previous error no longer occurs. This is fantastic!

Thank you so much for your swift and dedicated efforts in resolving this issue. Projectable is an amazing tool, and I am looking forward to integrating it into my workflow.

As the problem is addressed, I will go ahead and close this issue. Once again, thank you for your exceptional support!
