### ISSUE TITLE
Default config

### ISSUE THREAD

**Issue by fresh2dev** [dzfrias/projectable#10]
I thought I'd share the small changes I made to my projectable config to make it more comfortable/intuitive for me. Of course, these changes are based off my opinions and perspective, so feel free to ignore this.

https://gist.github.com/fresh2dev/0c732dfd3750d9a187b441497d42320b

Changes:

- allow many commands/special_commands to be defined in long-form using `[commands]` / `[special_commands]` blocks instead of single-line mapping.
- kill background processes with `ctrl-x` rather than `ctrl-c`.
- scroll the preview pane with `ctrl-j/k` instead of `ctrl-d/u` # more vim-friendly
- show hidden by default
- scroll up/down three with `ctrl-u/d` instead of `ctrl-n/p` # more vim-friendly
- execute a command with `:` instead of `e`  # more vim-friendly
- intuitive colors for git modifications:  added=green, new=red, and modified=yellow. Marks are cyan.

P.S., please take the number of issues I'm submitting as a form of flattery, projectable is exciting!

**Comment by dzfrias** [comment]
These look awesome! I agree - long-form is probably best for `[commands]` and `[special_commands]`. I'll try to enforce that style more in [CONFIG.md](https://github.com/dzfrias/projectable/blob/main/extras/CONFIG.md). I think the default git coloring also probably deserves a change.

Thank you for all the changes you suggested in the issues, they've really helped out!

**Comment by fresh2dev** [comment]
Glad some of my suggestions were helpful. Thank you for being attentive and swift, and for creating this exciting tool :clinking_glasses:
