### ISSUE TITLE
dirs_first config option seems to be doing nothing

### ISSUE THREAD

**Issue by gira93** [dzfrias/projectable#14]
The `dirs_first` config option should sort files putting directories first (since it's not documented I don't know if it should be doing that), the default is `true` but no matter the option set, it seems that directories always comes last in the listing.

projectable 1.1.0
rustc 1.70.0
Compiled on ARM64

**Comment by dzfrias** [comment]
Whoops, sorry about that! `dirs_first` is something I planned on implementing later, and I never intended for it to be officially in the docs. I'm working on implementing it right now, and it should be usable in a new release very soon, probably sometime today. I apologize for the confusion, and thanks for helping point this out for me.

**Comment by dzfrias** [comment]
`dirs_first` should work on HEAD now! It'll be in a release later today.
