### ISSUE TITLE
The --write-config command flag generates an invalid config file

### ISSUE THREAD

**Issue by gira93** [dzfrias/projectable#15]
Running `prj --write-config` generates an invalid default config file, prj complains about an invalid option `move` inside the config file.

projectable 1.1.0
rustc 1.70.0
Compiled on ARM64

**Comment by dzfrias** [comment]
It should be `move_path`. I'll fix this in the release later today!

**Comment by dzfrias** [comment]
Should be fixed as of v1.2.0!
