### ISSUE TITLE
editor configuration

### ISSUE THREAD

**Issue by Absobel** [dzfrias/projectable#17]
So I don't know if I missed something in the readme or config.md but I had to search in the code to see that the EDITOR variable had to be set if I wanted to use something other than vi when selecting files. Would it be possible to add a config option to set the command for the editor in the config file ? And if nothing is set, use the EDITOR variable, and if it's not set, vi.

**Comment by Absobel** [comment]
Tried doing contributing for the first time in my life to an open source project, so I don't know if I've done things right ^^' 
https://github.com/dzfrias/projectable/pull/18

**Comment by dzfrias** [comment]
Looks great, and it works for me too! Thanks for contributing!
