### ISSUE TITLE
Opening large folder crashes

### ISSUE THREAD

**Issue by thomas9911** [dzfrias/projectable#26]
Starting after a clean install

```sh
$ prj --version
projectable 1.3.0
$ prj
Error: error during app runtime

Caused by:
    0: error starting filesystem refresh watcher
    1: OS file watch limit reached. about ["/home/thomas/.cache/yarn/v6/npm-@babel-runtime-7.17.2-66f68591605e59da47523c631416b18508779941-integrity/node_modules/@babel/runtime/helpers/esm"]
```

Maybe it is possible to limit folder nesting

**Comment by dzfrias** [comment]
Hmm. I believe this will be fixed after 52da9b4 is released! If not, let me know and I can look into the issue further. If you want to see if it works, you can install from HEAD, too

**Comment by thomas9911** [comment]
indeed now installed from main and it loads :ok_hand: 

Maybe another problem, I was now scrolling through my folder and I have a binary file that is 27GB. Cat is trying to print it but ofcourse crashes :P Maybe there should be a file limit before 'cat'ing the file?

**Comment by dzfrias** [comment]
Ah good idea! I could try implementing a file size limit of sorts. I'm not sure what an appropriate size would be, though.

**Comment by thomas9911** [comment]
I have a csv file that is 1MB that resolves instantly so that could be a nice limit? projectable is mostly for programming / text files right?

**Comment by dzfrias** [comment]
Yeah. One megabyte sounds like a good limit to me, as well!
