### ISSUE TITLE
Change: `escape` should not close the TUI

### ISSUE THREAD

**Issue by fresh2dev** [dzfrias/projectable#4]
As a heavy user of `vim`, I am trigger-happy with the escape key. While evaluating projectable, I accidentally closed it more than I want to admit. Intuitively, I expect `escape` to operate as a sort of back-button. If I repeatedly slam `esc`, `esc`, esc`, ... I hope/expect  to end up at the top of the file browser with all directories collapsed.

**Comment by dzfrias** [comment]
That's understandable, and honestly I was having the same issues. I added escape as a global quit trigger, as "q" doesn't work in input boxes. I'll implement a setting to turn this behavior off.

**Comment by dzfrias** [comment]
Added the `esc_to_close` option!
