### ISSUE TITLE
Change: `ctrl-c` *should* close the TUI

### ISSUE THREAD

**Issue by fresh2dev** [dzfrias/projectable#5]
`ctrl-c` is the ubiquitous keybinding to kill a process. When evaluating projectable, I found myself slamming `ctrl-c` many times to exit before remembering to reach up and tap `q` (or escape! https://github.com/dzfrias/projectable/issues/4). I understand that projectable is intercepting `ctrl-c` and using it to kill background processes, but perhaps another mapping could be used to do that.

**Comment by dzfrias** [comment]
With the ability to bind multiple actions to the same key, this should be easy with a few config changes. The multi-key to action feature is almost ready!

When I push the feature, you should be able to do this in the config:
```toml
quit = ["ctrl-c", "q"]
kill_processes = "Q" # Or whatever you want
```

I could also make this a default, but I'm trying to keep the keys as stable as possible.

**Comment by dzfrias** [comment]
This is now possible as of 279c152fa6978fd194fb69fd73e32686cb762856!
