### ISSUE TITLE
Change: deletion prompt should default to "no"

### ISSUE THREAD

**Issue by fresh2dev** [dzfrias/projectable#7]
Call me paranoid, but the deletion prompt defaulting to "confirm" freaks me out. Further, the confirmation dialog would benefit from using the simplest terms "Yes" and "No", with the prompt defaulting to "No".

**Comment by dzfrias** [comment]
Another great suggestion! You're completely right; definitely a scary default when entire directories can be permanently removed with the click of a button.

**Comment by dzfrias** [comment]
Implemented this, should be available in the upcoming v1.1.0
