### ISSUE TITLE
Feature: using same key to toggle behaviors

### ISSUE THREAD

**Issue by fresh2dev** [dzfrias/projectable#8]
The same keybinding should be able to *toggle* specific behavior.

For example, if `m` is to mark, I expect `m` to *unmark* a file that is already marked.

`t` should activate -- or deactivate -- the git-diff view.

`o` should expand all -- or collapse all -- of the directories.

etc.

**Comment by dzfrias** [comment]
Great suggestion! I'll look into implementing this for marks. `t` does this already. On the subject of `o`, I don't think this is great as a toggle, as you don't need all directories open for it to still do something effective. For example, if you had one directory open and press `o`, the current behavior is to open all the rest, which I think is best. I can, however, make it so when **all** the directories are open and `o` is pressed, it closes everything.

**Comment by dzfrias** [comment]
I made it so `m` toggles marks. It'll be available in v1.1.0!

Thanks again for all your suggestions and feedback - they've already improved projectable a lot!

**Comment by fresh2dev** [comment]
Wicked!

> I can, however, make it so when **all** the directories are open and `o` is pressed, it closes everything.

This is reasonable. Generally speaking, if I press a key to do something, but that something is already done, then do the opposite of that something -- where it makes sense, of course.
