### ISSUE TITLE
Feature: fuzzy filter special-commands view

### ISSUE THREAD

**Issue by fresh2dev** [dzfrias/projectable#9]
The special-commands listing of custom commands is very nice! I found myself defining many commands under a catch-all glob pattern `*`. I could see this view getting long quickly. The ability to fuzzy-find a command in this view would be killer :metal:

**Comment by dzfrias** [comment]
Great suggestion! I'll look into writing this in at some point!

**Comment by fresh2dev** [comment]
Hot damn! :star_struck:
